import { Injectable, Inject } from '@angular/core';

// packaged used for local/session browser storage
import { SESSION_STORAGE, StorageService } from "ngx-webstorage-service";

const MYT_ADMIN_SESSION_KEY = 'myt-admin-token';  // session storage key to authenticate users
const MYT_ADMIN_NAME_KEY = 'myt-admin-name';      // session storage key to welcome users by full name

@Injectable({
  providedIn: 'root'
})
export class BrowserStorageService {

  constructor(@Inject(SESSION_STORAGE) private storage: StorageService) { }

  /**
   * Set session storage login key and value by using login token generated by webservice
   * 
   * @loginToken Username of user in session
   */ 
  public setSessionLoginKey(loginToken: string): void{
    // check if session is set already and remove it to set another
    if(this.storage.has(MYT_ADMIN_SESSION_KEY)){
      this.storage.remove(MYT_ADMIN_SESSION_KEY);
      this.storage.set(MYT_ADMIN_SESSION_KEY, loginToken);
    }else{  // set the storage key if not exist
      this.storage.set(MYT_ADMIN_SESSION_KEY, loginToken);
    }
  }

   /**
    * Get the value of session login key or return false if not exist
   */ 
   public getSessionLoginKey(): any{
    // check if session key is set already and get the value
    if(this.storage.has(MYT_ADMIN_SESSION_KEY)){
        return this.storage.get(MYT_ADMIN_SESSION_KEY);
    }else{
      return false;
    }
  }

  /**
   * Set session storage admin name key and value by using admin name from webservice
   * 
   * @adminName Full name of user in session
   */ 
  public setSessionUserKey(adminName: string): void{
      // check if session is set already and remove it to set another
      if(this.storage.has(MYT_ADMIN_NAME_KEY)){
        this.storage.remove(MYT_ADMIN_NAME_KEY);
        this.storage.set(MYT_ADMIN_NAME_KEY, adminName);
      }else{  // set the storage key if not exist
        this.storage.set(MYT_ADMIN_NAME_KEY, adminName);
      }
  }

     /**
    * Get the value of session admin name key or return false if not exist
   */ 
  public getSessionUserKey(): any{
    // check if session key is set already and get the value
    if(this.storage.has(MYT_ADMIN_NAME_KEY)){
        return this.storage.get(MYT_ADMIN_NAME_KEY);
    }else{
      return false;
    }
  }

}
